
language: python
sudo: required
dist: trusty
#user container-based infrastructure
before_install:
# install dependencies
  - install: "pip install -r requirements.txt"  
  - pip install robotframework
#python:
#  - "2.7"
script: pybot test_google.robot
