
language: python
python:
  - 3.6

env:
  - PIPENV_VENV_IN_PROJECT=1
  - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv pew
  - pipenv --three
  - pipenv install git+https://github.com/hmmlearn/hmmlearn.git
  - pipenv install
  - pip install robotframework

script: pybot test_google.robot
