language: python
sudo: required
dist: trusty
#user container-based infrastructure
before_install:
# install dependencies
install: "pip install -r requirements.txt"  
python:
  - "3.0"
script: pybot test_google.robot
